FROM node:14-alpine

RUN apk add --no-cache fontconfig

WORKDIR /app

COPY ./package.json         /app/package.json
COPY ./package-lock.json    /app/package-lock.json
COPY ./index.test.js        /app/index.test.js

RUN npm ci
