FROM node:18-slim

RUN apt-get update && apt-get install -y -q libfontconfig1

WORKDIR /app

COPY ./package.json         /app/package.json
COPY ./package-lock.json    /app/package-lock.json
COPY ./index.test.js        /app/index.test.js

RUN npm ci
