# This is a basic workflow to help you get started with Actions
name: Run

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    inputs: {}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [14, 16, 18, 20]
        distribution: ["alpine", "alpine-font", "slim"]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Print Dockerfile
        run: cat Dockerfile.${{ matrix.version }}-${{ matrix.distribution }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        run: docker build . -f Dockerfile.${{ matrix.version }}-${{ matrix.distribution }} -t skia-canvas:${{ matrix.version }}-${{ matrix.distribution }}

      - name: List images
        run: docker images ls

      - name: Run test
        uses: addnab/docker-run-action@v3
        with:
          image: "skia-canvas:${{ matrix.version }}-${{ matrix.distribution }}"
          run: npm test

      # - uses: addnab/docker-run-action@v3
      #   with:
      #     image: node:${{ matrix.version }}-${{ matrix.distribution }}
      #     run: echo "hello world"
